export const COMPLAINT_STATUS = {
  PENDING_REVIEW: "PENDING_REVIEW",
  GENUINE: "GENUINE",
  NOT_GENUINE: "NOT_GENUINE",
  ASSIGNED: "ASSIGNED",
  IN_PROGRESS: "IN_PROGRESS",
  RESOLVED: "RESOLVED",
  CLOSED: "CLOSED",
};
